spring:
  #mysql四要素
  datasource:
    url: jdbc:mysql://localhost:3306/steam?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis配置
  data:
    redis:
      host: 127.0.0.1           #redis地址
      port: 6379                #端口号
      lettuce:
        pool:
          max-active: 20        #最大连接数
          max-idle: 10          #最大空闲连接
          min-idle: 2           #最小空闲连接
          max-wait: 10000       #没有连接时的等待时长
  #项目名称
  application:
    name: Steam
#项目端口
server:
  port: 8081
